apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maven-webapp-blue
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/hareesh88666/maven-webapp-gitops.git
    targetRevision: main
    path: maven-webapp
    helm:
      valueFiles:
        - values-blue.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

